name: Manage Milestone On Release

on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  issues: write
  pull-requests: write

env:
  github-token: ${{secrets.GITHUB_TOKEN}}

jobs:
  on-release:
    runs-on: ubuntu-latest
    steps:
      - name: parameters
        id: parameters
        run: |
          echo "today=$(date +%Y/%m/%d)" >> "$GITHUB_OUTPUT"
      - name: get milestone
        id: get_milestone
        uses: actions/github-script@v6
        with:
          script: |
            console.log('現在のマイルストーンを取得します')
            const reg = new RegExp("Merged Pull Requests .+ ~")
            const listParams = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              sort: "due_on",
              direction: "desc",
              state: "open",
            }
            console.log('call github.rest.issues.listMilestones()')
            console.log(listParams)
            const milestones = await github.rest.issues.listMilestones(listParams)
            const milestone = milestones.data.find(({ title }) => title.match(reg)) || null
            if (milestone) {
              console.log('マイルストーンが見つかりました')
              console.log(milestone)
              return milestone
            } else {
              console.log('マイルストーンが見つかりませんでした')
              return false
            }
      - name: close prev milestone
        uses: actions/github-script@v6
        if: ${{ steps.get_milestone.outputs.result }} != false
        with:
          script: |
            console.log('現在のマイルストーンをクローズします')
            const today = new Date().toLocaleDateString("ja-JP", {year: "numeric",month: "2-digit",day: "2-digit"}).replaceAll('/', '-')
            const milestone = ${{ steps.get_milestone.outputs.result }}
            const updateParams = {
              owner: context.repo.owner, repo: context.repo.repo,
              milestone_number: milestone.number, state: 'closed',
              title: milestone.title + ' ' + today, description: milestone.description + ' ' + today,
            }
            console.log('call github.rest.issues.updateMilestone()')
            console.log(updateParams)
            const result = await github.rest.issues.updateMilestone(updateParams)
            console.log(result)
      - name: create next milestone
        id: create_milestone
        uses: actions/github-script@v6
        with:
          script: |
            console.log('次回のマイルストーンを作成します')
            const today = new Date().toLocaleDateString("ja-JP", {year: "numeric",month: "2-digit",day: "2-digit"}).replaceAll('/', '-')
            const createParams = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "Merged Pull Requests " + today + " ~",
              description: today + " ~",
            }
            console.log('call github.rest.issues.createMilestone()')
            console.log(createParams)
            const milestone = await github.rest.issues.createMilestone(createParams)
            return milestone.data
