name: Create Release
on:
  workflow_dispatch:
  push:
    branches:
      # - test
      - 40-リリースノート自動化の検証
    # types:
    #   - closed
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Bump version and push tag
        id: bump_version
        uses: phips28/gh-action-bump-version@master
        with:
          tag-prefix: "v"
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.bump_version.outputs.tag }}
          release_name: Release ${{ steps.bump_version.outputs.tag }}
          draft: false
          prerelease: false
